spring:
  datasource:
    url: jdbc:postgresql://ziro-postgres:5432/ziro_db
    username: ziro_user
    password: ziro_pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  address: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    key-store: file:/app/keystore/ziro-backend.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ziro-backend

logging:
  level:
    liquibase: DEBUG
